[package]
name = "Json_rpc"
version = "0.1.0"
authors = ["LiuZhuo"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
jsonrpc-http-server = "14.1"

[dev-dependencies]
env_logger = "0.7"
